### PR TITLE
feat: add support for playback speed

### LINKED ISSUE #3: Add option to set playback speed / pitch
Hi thanks for this library I would like to have the feature to set pitch and playback speed.
Android has the API here: https://developer.android.com/reference/android/media/PlaybackParams#setPitch(float)

### PR DESCRIPTION
**Pull request by ShivamJoker**
Closes #3

### CODE REVIEW

**Comment by vokhuyetOz** [comment]
LGTM

**Comment by vokhuyetOz** [comment]
i can not run android successfully
i  will publish new version after running successfully

**Comment by ShivamJoker** [comment]
> i can not run android successfully
> i  will publish new version after running successfully
> 

I tested in example app, it worked fine.

**Comment by ShivamJoker** [comment]
@vokhuyetOz can you please release this new version?
I am unable to release my app without this.

**Comment by vokhuyetOz** [comment]
ok, i'll create new version first and update it later

**Comment by vokhuyetOz** [comment]
published in 0.0.10

**Pull request merged**
